name: git_mobile
description: "Git Mobile using Flutter"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #StateManagements
  provider: ^6.1.1

  #Networks
  connectivity_plus: ^5.0.2
  http:
  cached_network_image:
  firebase_core:
  cloud_firestore:
  github_sign_in_plus: ^0.0.2

  #Local Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.1.0

  #Widgets
  size_setter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  device_preview:

flutter:
  uses-material-design: true

  fonts:
    - family: InterRegular
      fonts:
        - asset: fonts/Inter/Inter-Regular.ttf
    - family: InterMedium
      fonts:
        - asset: fonts/Inter/Inter-Medium.ttf

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/json/language/